-- MySQL Script generated by MySQL Workbench
-- Wed Jun 21 12:03:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbVentas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbVentas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbVentas` DEFAULT CHARACTER SET utf8 ;
USE `dbVentas` ;

-- -----------------------------------------------------
-- Table `dbVentas`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVentas`.`Vendedor` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbVentas`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVentas`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `fk_idVendedor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Peso` DECIMAL(11,2) NULL,
  `Descripcion` VARCHAR(300) NULL,
  `PrecioCosto` DECIMAL(11,2) NOT NULL,
  `PrecioVenta` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Vendedor_idx` (`fk_idVendedor` ASC),
  CONSTRAINT `fk_Producto_Vendedor`
    FOREIGN KEY (`fk_idVendedor`)
    REFERENCES `dbVentas`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
